plugins {
    id 'application'
}

group = 'com.stats'
version = '1.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
    maven { url 'https://jitpack.io' }   // liefert com.github.dnoble539:MathLib
}

dependencies {
    implementation 'com.github.dnoble539:MathLib:v1.1.0'

    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
    testImplementation 'org.junit.jupiter:junit-jupiter-params:5.10.2'
    testImplementation 'org.assertj:assertj-core:3.25.2'
}

application {
    mainClass = 'Application'
}

test {
    useJUnitPlatform()
}
